# Site settings
title: "This Week in VC4"
description: ""
url: "https://anholt.github.io/twivc4"
baseurl: ""
google_analytics: 

#  Build settings
permalink: pretty
paginate: 10

twitter:
  username: anholt

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
