# Site settings
title: "This Week in VC4/VC5"
description: ""
url: "https://anholt.github.io"
baseurl: "/twivc4"
google_analytics: 

#  Build settings
permalink: pretty
paginate: 10

twitter:
  username: anholt

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
